#
### configure a yabe instance
#
#
#### Add your settings here
#
# `set [setting:] [value]`
#
#
#     author:     John Doe                                # blog author
#     title:      a blog about ...                        # site title
#     date:       yyyy-mm-dd                              # date format for articles
#     disqus:     ''                                      # disqus id, or ''
#     ext:        markdown                                # file extension for articles
#     summary:                                            # length of article summary and delimiter
#       max: 150
#       delim: \n##
#
#
author:       John Doe
title:        Sammo
url:          /
description:  Say hello to Sammo, a theme crafted with a tiny Sammy.js application that use pushState to handle page transitions
format:       f
disqus:       ''
ext:          markdown
summary:
  delim: '<!--more-->|##'
github:
  user: mklabs
  ext: markdown


